name: Lint
on: pull_request

jobs:
  markdown:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: '_posts/,docs/stable/'
          separator: ","
          filter_mode: added
          fail_on_error: false
      - uses: articulate/actions-markdownlint@main
        with:
          config: .markdownlint.jsonc
          files: 'docs/stable/**/*.md _posts/*.md'

  python:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable
      with:
        options: "--check --skip-string-normalization --verbose --diff --color"
        src: "./scripts"
        version: "24.8.0"
